name: Gfortran

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install
        run: |
          #./install_gfortran.sh -p $HOME/gfortran -w no -j 4
          #cp ./clean_rpath.sh $HOME/gfortran
          #rm -rf *
          #cd $HOME/gfortran
          #find . -name "*.la" -exec rm {} \;
          #rm -rf lib/pkgconfig share/info
          #./clean_rpath.sh
          #rm -f clean_rpath.sh
          #cd $HOME
          #zip -r gfortran.zip gfortran
          #echo "Finished zip"
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test
          asset_id=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test | grep -B 2 -m 1 gfortran.zip | grep '"id"' | awk '{print $2}' | tr -d ',')
          echo $asset_id
          [ ! -z "$asset_id" ] && curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/gautierbureau/dynawo-macos/releases/assets/${asset_id}
          echo "delete done"
          upload_url=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
          echo "$upload_url done"
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/zip' -X POST ${upload_url}?name=gfortran.zip --data-binary @gfortran.zip
