name: OMC Packages

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install
        run: |
          ./install_omc.sh -p $HOME/dynawo-macos-package -j 4
          cp ./clean_rpath.sh $HOME/dynawo-macos-package
          cd $HOME/dynawo-macos-package
          ./clean_rpath.sh
          rm -rf share/man share/doc lib/pkgconfig bin/autopoint bin/gettextize lib/gettext/user-email lib/*.la
          rm -f clean_rpath.sh
          cd $HOME
          zip -r package.zip dynawo-macos-package
          asset_id=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test | grep -B 2 -m 1 package.zip | grep '"id"' | awk '{print $2}' | tr -d ',')
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/gautierbureau/dynawo-macos/releases/assets/${asset_id}
          upload_url=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/zip' -X POST  ${upload_url}?name=package.zip --data-binary @package.zip
