name: OMC Packages

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install
        run: |
          ./install_omc.sh -p $HOME/install -j 4
          cd $HOME
          zip -r package.zip install
          url=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-macos/releases/tags/test | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
          echo $url
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/zip' -X POST  https://uploads.github.com/repos/gautierbureau/dynawo-macos/releases/26359298/assets?name=package.zip --data-binary @package.zip
